/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"fullscreen-exit" | "fullscreen" | "login-bg" | "login-box-bg" | "search">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"fullscreen-exit" | "fullscreen" | "login-bg" | "login-box-bg" | "search">;
          default: string;
          required: true;
      };
  }>>, {
      name: "fullscreen-exit" | "fullscreen" | "login-bg" | "login-box-bg" | "search";
  }>;
  export const svgNames: ["fullscreen-exit", "fullscreen", "login-bg", "login-box-bg", "search"];
  export type SvgName = "fullscreen-exit" | "fullscreen" | "login-bg" | "login-box-bg" | "search";
  export default SvgIcon;
}
